### ISSUE TITLE
dockerize

### ISSUE THREAD

**Issue by slively** [MVPStudio/build_setup#14]
Create a Dockerfile that inherits from a base python container (`python:3.7.2-stretch`), 
 installs the google cloud sdk, and copies over all the bulid_setup files.

Installing the google sdk in the image can probably be copy/pasted from Googles official image: https://hub.docker.com/r/google/cloud-sdk/dockerfile

It should also create an alias in the ~/.bash_profile for the build_setup script.
That way CircleCI can run the container and inside it a user just needs to do something like:
```bash
cd /build-output
build_tag_publish_deploy
```
Or if their yaml is not in the default directory
```bash
cd /build-output
build_tag_publish_deploy /some/path/to/my/yaml
```

All the environment variables used by the script would be setup for them.

**Comment by slively** [comment]
In the end hopefully a circlci build could be this "simple":
```yaml
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn build
      - persist_to_workspace:
          root: ./
          # must include anything needed by the Dockerfile, mvpstudio.yml, .git, and kube folder
          paths:
            - build
            - Dockerfile
            - .mvpstudio
            - .git
            - kube

  publish:
    docker:
      - image: mvpstudio/publish-deploy
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ./
      - run: build_tag_publish_deploy

workflows:
  version: 2
  build-publish-deploy:
    jobs:
      - build
      - deploy:
          context: build-publish-deploy
          requires:
            - build
          filters:
            branches:
              only: master
```
